# Generated by Django 4.2.23 on 2025-08-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='isAvailable',
            new_name='disponivel',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='preco',
        ),
    ]
