# Generated by Django 4.2.23 on 2025-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_isavailable_item_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco',
            field=models.CharField(max_length=5),
        ),
    ]
