# Generated by Django 4.2.23 on 2025-07-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_produto_pedido_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='obersarvacao',
            new_name='observacao',
        ),
    ]
